# Generated by Django 3.0.2 on 2020-01-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='Inventory.Building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Inventory.Flat'),
        ),
        migrations.AlterField(
            model_name='roomitems',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.Room'),
        ),
    ]
