# Generated by Django 3.0.2 on 2020-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20200129_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitems',
            name='cost',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
